server:
  port: 8082

spring:
  application:
    name: erp
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/jmi?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    tomcat:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    jedis:
      pool:
        maxActive: 20
        maxWait: 3000
        maxIdle: 20
        minIdle: 0
  jackson:
    time-zone: GMT-8
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: true
mybatis-plus:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    typeAliasesPackage: com.naswork.erp.entity
#    typeEnumsPackage: com.naswork.erp.entity.enums
    global-config:
       id-type: 2
       field-strategy: 2
       db-column-underline: true
       refresh-mapper: true
#       capital-mode: true
#       key-generator:
       logic-delete-value: 0
       logic-not-delete-value: 0
       sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
       meta-object-handler:
    configuration:
       map-underscore-to-camel-case: true
       cache-enabled: false

logging:
  config: classpath:logback.xml


